app = "whitehatmirror"

primary_region = "sin"  # or your chosen region

[build]
  image = "python:3.11"

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 442
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
