services:
  - type: worker
    name: whitehat-mirror-backend
    runtime: python
    env: python
    plan: free
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
